### ISSUE TITLE
更改一用户密码可见状态后，切换用户，密码可见状态保持，但是输入密码不可见

### ISSUE THREAD

**Issue by CrossCC** [ukui/ukui-greeter#12]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-2020022402-amd64.iso
测试环境：兆芯E台式机、联想T490

测试步骤：
1. 登录界面，点击密码输入框右侧的眼睛，输入密码变为可见
2. 点击头像左侧的返回
3. 再点击任意用户

预期结果：更换用户之后，密码状态变为默认不可见。或者密码状态为可见且输入的密码可见

实际结果：更换用户后，密码状态保持之前更改，为可见，但是输入密码后不可见。

**Comment by liuyuanpeng176** [comment]
已解决，更换用户后密码状态重新改为不可见且输入的密码不可见

**Comment by liumin0322** [comment]
20200328版本测试通过。
