### ISSUE TITLE
系统多于3个用户，且上次登录为第一个用户时，登录界面只展示3个用户。

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-greeter#19]

**Comment by liuyuanpeng176** [comment]
下周将改为循环显示，添加鼠标移到头像上时头像变大效果，在用户较多时，在左右添加显示箭头提示用户还有其它用户可选择

**Comment by liuyuanpeng176** [comment]
已改为在有头像未显示出来时，在未显示出来的一侧显示一个箭头，提示该侧方向任然有其它用户可供选择，可通过鼠标点击箭头或者头像，或者使用左右方向键进行切换

**Comment by liumin0322** [comment]
20200402-beta版本测试通过。
