### ISSUE TITLE
Create a new user test123, the login interface is displayed: test ...

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-greeter#20]
创建新用户test123，登录界面显示为test...

测试步骤：
1、控制面板中创建新用户test123和test456
2、点击开始菜单-电源-切换用户
3、切换用户界面，两个用户均显示为test...

**Comment by liuyuanpeng176** [comment]
和分辨率大小有关系，当用户名长度超过头像宽度时，会将超出部分变为“。。。”，接下来是否应该通过调整字体大小或者用户名较长时显示两行来解决 ?  尽量使能显示出来的用户名长点，如果还是长的话，就用。。。来隐藏超出部分

**Comment by liuyuanpeng176** [comment]
通过将用户名的字体大小改小解决了这个问题。

**Comment by liumin0322** [comment]
20200328版本测试通过。
