### ISSUE TITLE
登录界面，新创建用户头像显示为反差色

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-greeter#21]

**Comment by liuyuanpeng176** [comment]
通过控制面板新建用户，用户默认使用控制面板提供的头像，头像是不透明的。登录界面读到的就是这个头像。如果是通过命令新建的用户，用户是不带有头像的，登录获取不到头像就会使用自带的头像，登录自带的头像是有透明的。就有了反差

**Comment by liumin0322** [comment]
Tested pass in the 20200410 version
