### ISSUE TITLE
Locale always set to zh_TW.big5

### ISSUE THREAD

**Issue by felixonmars** [ukui/ukui-greeter#24]
I didn't find a clue, but when using ukui-greeter the locale-related environment variables (LANG/LC_*) are always set to zh_TW.big5 which breaks a lot of settings.

I didn't find the setting on the UI of latest ukui-greeter, too.

**Comment by liuyuanpeng176** [comment]
I haven't encountered such a problem, can you provide more details?

**Comment by xiaodongliu-nudt** [comment]
@felixonmars can you provide more details about how to reproduce this issue?

**Comment by felixonmars** [comment]
Seems like ukui-greeter always follow gdm settings on this.

**Comment by felixonmars** [comment]
Closing as such issue doesn't seem to come from UKUI side. Sorry for the trouble!
