### ISSUE TITLE
在登录界面，点击屏幕键盘后，挡住输入密码框

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-greeter#34]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200309-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、在登录界面，点击右下角屏幕键盘按钮

预期结果：屏幕显示正常

实际结果：屏幕键盘挡住输入密码框

**Comment by liuyuanpeng176** [comment]
重新调整了低分辨率下的间距和布局。

**Comment by liumin0322** [comment]
Tested pass in the 20200410 version
