### ISSUE TITLE
多用户的情况下，登录界面切换用户非常卡

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-greeter#36]

**Comment by liuyuanpeng176** [comment]
多用户是指创建了多个用户，登录界面卡？还是已经登录了多个用户，登录界面卡呢？如果是登录了多个用户，可能是进程太多导致了卡，桌面上的应用是否也会卡呢？ @liumin0322

**Comment by liumin0322** [comment]
创建了多个用户，未登录
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by liuyuanpeng176** [comment]
重新优化了下，目前我这里没有出现了。

**Comment by liumin0322** [comment]
Tested pass in the 20200410 version
